# Generated by Django 4.2.7 on 2025-07-09 18:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=255)),
                ("headers", models.JSONField(default=dict)),
                ("query_params", models.JSONField(default=dict)),
                ("body", models.TextField()),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("response_data", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("invalid", "Invalid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("created_news_id", models.UUIDField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("remote_ip", models.GenericIPAddressField()),
                ("correlation_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Webhook Log",
                "verbose_name_plural": "Webhook Logs",
                "db_table": "webhook_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "endpoint_url",
                    models.URLField(
                        help_text="The URL where this webhook is accessible"
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(
                        help_text="Secret key for webhook verification", max_length=255
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "expected_content_type",
                    models.CharField(default="application/json", max_length=50),
                ),
                ("requires_authentication", models.BooleanField(default=True)),
                ("rate_limit_per_minute", models.IntegerField(default=100)),
                ("total_requests", models.BigIntegerField(default=0)),
                ("successful_requests", models.BigIntegerField(default=0)),
                ("failed_requests", models.BigIntegerField(default=0)),
                ("last_request_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Webhook Source",
                "verbose_name_plural": "Webhook Sources",
                "db_table": "webhook_source",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WebhookRetry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempt_number", models.IntegerField()),
                ("error_message", models.TextField()),
                ("next_retry_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "webhook_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retries",
                        to="webhooks.webhooklog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Retry",
                "verbose_name_plural": "Webhook Retries",
                "db_table": "webhook_retry",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="webhooklog",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="webhooks.webhooksource",
            ),
        ),
        migrations.CreateModel(
            name="WebhookStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_requests", models.IntegerField(default=0)),
                ("successful_requests", models.IntegerField(default=0)),
                ("failed_requests", models.IntegerField(default=0)),
                ("invalid_requests", models.IntegerField(default=0)),
                ("avg_processing_time", models.FloatField(default=0.0)),
                ("news_created", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webhooks.webhooksource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Statistic",
                "verbose_name_plural": "Webhook Statistics",
                "db_table": "webhook_statistic",
                "ordering": ["-date"],
                "unique_together": {("date", "source")},
            },
        ),
        migrations.AddIndex(
            model_name="webhooklog",
            index=models.Index(
                fields=["source", "-created_at"], name="webhook_log_source__66e1ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhooklog",
            index=models.Index(
                fields=["status", "-created_at"], name="webhook_log_status_4c4f22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhooklog",
            index=models.Index(
                fields=["remote_ip", "-created_at"],
                name="webhook_log_remote__459483_idx",
            ),
        ),
    ]
