# Generated by Django 4.2.7 on 2025-07-12 00:36

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="news",
            name="news_news_title_ad75b1_gin",
        ),
        migrations.RunSQL(
            # Create GIN index for full-text search
            "CREATE INDEX news_news_title_ad75b1_gin ON news_news USING gin(to_tsvector('portuguese', title || ' ' || content));",
            reverse_sql="DROP INDEX IF EXISTS news_news_title_ad75b1_gin;"
        ),
    ]
