# Generated by Django 4.2.7 on 2025-07-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_news_news_title_ad75b1_gin_and_more'),
    ]

    operations = [
        # First, update empty external_id values to NULL
        migrations.RunSQL(
            "UPDATE news_news SET external_id = NULL WHERE external_id = '';",
            reverse_sql="UPDATE news_news SET external_id = '' WHERE external_id IS NULL;"
        ),
        # Then alter the field to allow NULL
        migrations.AlterField(
            model_name='news',
            name='external_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]