global:
  scrape_interval: 2s
  evaluation_interval: 5s

rule_files:
  - "first_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'django'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 2s

  - job_name: 'django-celery'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/celery/metrics/'
    scrape_interval: 2s

  - job_name: 'django-security'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/security/metrics/'
    scrape_interval: 2s

  - job_name: 'django-business'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/business/metrics/'
    scrape_interval: 2s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']


  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']