# Generated by Django 4.2.7 on 2025-07-09 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("news", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("webhook", "Webhook"),
                            ("slack", "Slack"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Channel-specific configuration"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("rate_limit_per_minute", models.IntegerField(default=60)),
                ("rate_limit_per_hour", models.IntegerField(default=1000)),
                ("total_sent", models.BigIntegerField(default=0)),
                ("total_delivered", models.BigIntegerField(default=0)),
                ("total_failed", models.BigIntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Channel",
                "verbose_name_plural": "Notification Channels",
                "db_table": "notification_channel",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("urgent_news", "Urgent News"),
                            ("daily_summary", "Daily Summary"),
                            ("weekly_digest", "Weekly Digest"),
                            ("breaking_news", "Breaking News"),
                            ("category_alert", "Category Alert"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                (
                    "body_template",
                    models.TextField(
                        help_text="Template with placeholders like {{title}}, {{content}}, {{url}}"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("max_length", models.IntegerField(blank=True, null=True)),
                ("times_used", models.PositiveIntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="notifications.notificationchannel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "db_table": "notification_template",
                "ordering": ["channel", "template_type", "name"],
                "unique_together": {("channel", "template_type", "is_default")},
            },
        ),
        migrations.CreateModel(
            name="NotificationSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        help_text="Phone number, email, webhook URL, etc.",
                        max_length=255,
                    ),
                ),
                (
                    "min_priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        help_text="Minimum priority level to receive notifications",
                        max_length=10,
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        default=list, help_text="Keywords to filter notifications"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("urgent_only", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("notifications_received", models.PositiveIntegerField(default=0)),
                ("last_notification", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Only receive notifications for these categories",
                        to="news.category",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="notifications.notificationchannel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Subscription",
                "verbose_name_plural": "Notification Subscriptions",
                "db_table": "notification_subscription",
                "ordering": ["-created_at"],
                "unique_together": {("user", "channel", "destination")},
            },
        ),
        migrations.CreateModel(
            name="NotificationStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_sent", models.PositiveIntegerField(default=0)),
                ("total_delivered", models.PositiveIntegerField(default=0)),
                ("total_failed", models.PositiveIntegerField(default=0)),
                ("total_cancelled", models.PositiveIntegerField(default=0)),
                ("urgent_notifications", models.PositiveIntegerField(default=0)),
                ("high_notifications", models.PositiveIntegerField(default=0)),
                ("medium_notifications", models.PositiveIntegerField(default=0)),
                ("low_notifications", models.PositiveIntegerField(default=0)),
                ("avg_delivery_time", models.FloatField(default=0.0)),
                ("delivery_rate", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifications.notificationchannel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Statistic",
                "verbose_name_plural": "Notification Statistics",
                "db_table": "notification_statistic",
                "ordering": ["-date"],
                "unique_together": {("date", "channel")},
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("external_id", models.CharField(blank=True, max_length=255)),
                ("response_data", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "news",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="news.news",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="notifications.notificationsubscription",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifications.notificationtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="notificatio_status_e721a0_idx",
                    ),
                    models.Index(
                        fields=["subscription", "-created_at"],
                        name="notificatio_subscri_90685a_idx",
                    ),
                    models.Index(
                        fields=["priority", "-created_at"],
                        name="notificatio_priorit_39d983_idx",
                    ),
                    models.Index(
                        fields=["scheduled_for"], name="notificatio_schedul_f83d3c_idx"
                    ),
                ],
            },
        ),
    ]
